const CHAVE='cariocaTicketPainelUrlApi';let urlApi='';let ultimoTs=0;let instalarEvento=null;
document.addEventListener('DOMContentLoaded',()=>{registrar();urlApi=localStorage.getItem(CHAVE)||'';document.getElementById('api').value=urlApi;registrarSW();setInterval(()=>urlApi&&carregar(false),10000);setInterval(atualizarTempo,1000);urlApi?carregar(true):abrirConfig();});
function registrar(){document.getElementById('atualizar').onclick=()=>carregar(true);document.getElementById('config').onclick=abrirConfig;document.getElementById('tela').onclick=telaCheia;document.getElementById('testar').onclick=testar;document.getElementById('salvar').onclick=salvar;document.getElementById('instalar').onclick=instalar;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();instalarEvento=e;document.getElementById('instalar').classList.remove('oculto')});}
function registrarSW(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.log);}
async function instalar(){if(!instalarEvento)return;instalarEvento.prompt();await instalarEvento.userChoice;instalarEvento=null;document.getElementById('instalar').classList.add('oculto');}
function abrirConfig(){document.getElementById('modal').showModal();}
async function testar(){const u=normalizar(document.getElementById('api').value);if(!valida(u))return msg('URL inválida.',false);const antiga=urlApi;urlApi=u;try{const d=await buscar();validar(d);msg('Conexão realizada com sucesso.',true)}catch(e){msg(e.message,false)}finally{urlApi=antiga}}
async function salvar(){const u=normalizar(document.getElementById('api').value);if(!valida(u))return msg('A URL deve terminar em /exec.',false);urlApi=u;try{const d=await buscar();validar(d);localStorage.setItem(CHAVE,urlApi);preencher(d);mostrar();msg('Configuração salva.',true);setTimeout(()=>document.getElementById('modal').close(),700)}catch(e){msg(e.message,false)}}
async function carregar(visual){if(!urlApi)return abrirConfig();if(visual)document.getElementById('carregando').classList.remove('oculto');try{const d=await buscar();validar(d);preencher(d);mostrar()}catch(e){const x=document.getElementById('erro');x.textContent='❌ '+e.message;x.classList.remove('oculto')}finally{document.getElementById('carregando').classList.add('oculto')}}
function buscar(){return new Promise((ok,erro)=>{const cb='ct_'+Date.now();const s=document.createElement('script');const t=setTimeout(()=>{limpar();erro(new Error('Tempo esgotado na conexão.'))},15000);function limpar(){clearTimeout(t);delete window[cb];s.remove()}window[cb]=d=>{limpar();ok(d)};s.onerror=()=>{limpar();erro(new Error('Falha ao acessar a API.'))};s.src=urlApi+'?action=painel&callback='+cb+'&_='+Date.now();document.body.appendChild(s)})}
function validar(d){if(!d||d.sucesso!==true)throw new Error((d&&d.mensagem)||'Resposta inválida da API.')}
function preencher(d){const e=d.evento||{},r=d.resumo||{};txt('eventoNome',e.nome||'Evento');txt('eventoData','📅 '+(e.data||'—'));txt('eventoHorario','🕒 '+(e.horario||'—'));txt('eventoLocal','📍 '+([e.local,e.cidade,e.uf].filter(Boolean).join(' — ')||'—'));txt('atualizado',d.atualizadoEm||'agora');txt('presentes',r.presentes||0);txt('pendentes',r.pendentes||0);txt('receita',r.receita||'R$ 0,00');txt('pagos',(r.ingressosPagos||0)+' pagos');txt('validos',r.ingressosValidos||0);txt('emitidos',(r.totalIngressos||0)+' emitidos');txt('ticket',r.ticketMedio||'R$ 0,00');txt('cortesias',(r.cortesias||0)+' cortesias');txt('cancelados',r.cancelados||0);txt('vagas',r.capacidadeConfigurada?r.vagasRestantes:'—');txt('capacidade',r.capacidadeConfigurada?'Capacidade: '+r.capacidade:'Capacidade não configurada');ultimo(d.ultimoCheckin);lista(d.checkinsRecentes||[]);barras(r);grafico(d.checkinsPorHora||[])}
function ultimo(i){const a=document.getElementById('ultimo');if(!i){a.classList.add('vazio');txt('ultimoNome','Nenhum check-in');txt('ultimoTipo','—');txt('ultimoHorario','—');txt('ultimoCodigo','—');txt('ultimoTempo','—');ultimoTs=0;return}a.classList.remove('vazio');txt('ultimoNome',i.nome);txt('ultimoTipo',i.tipo);txt('ultimoHorario',i.horario);txt('ultimoCodigo',i.codigo);ultimoTs=Number(i.timestamp||0);atualizarTempo()}
function lista(l){document.getElementById('lista').innerHTML=l.length?l.map(i=>'<div class="item"><div class="avatar">'+iniciais(i.nome)+'</div><div><b>'+esc(i.nome)+'</b><br><small>'+esc(i.tipo)+' • '+esc(i.codigo)+'</small></div><small>'+hora(i.horario)+'</small></div>').join(''):'Nenhum check-in registrado.'}
function barras(r){const o=Math.max(0,Math.min(100,Number(r.percentualOcupacao||0))),c=Math.max(0,Math.min(100,Number(r.percentualCheckin||0)));txt('ocupacaoPct',r.capacidadeConfigurada?o+'%':'—');txt('checkinPct',c+'%');document.getElementById('ocupacaoBarra').style.width=r.capacidadeConfigurada?o+'%':'0%';document.getElementById('checkinBarra').style.width=c+'%';txt('ocupacaoTexto',(r.ingressosValidos||0)+' válidos');txt('vagasTexto',r.capacidadeConfigurada?(r.vagasRestantes||0)+' vagas':'Capacidade não configurada');txt('checkinTexto',(r.presentes||0)+' de '+(r.ingressosValidos||0)+' ingressos válidos')}
function grafico(l){const g=document.getElementById('grafico');if(!l.length){g.innerHTML='Nenhum check-in registrado.';return}const m=Math.max(...l.map(x=>Number(x.quantidade||0)));g.innerHTML=l.map(x=>'<div class="coluna"><b>'+x.quantidade+'</b><i style="height:'+Math.max(4,Math.round(x.quantidade/m*150))+'px"></i><small>'+esc(x.hora)+'</small></div>').join('')}
function atualizarTempo(){if(!ultimoTs)return;const s=Math.max(0,Math.floor((Date.now()-ultimoTs)/1000));let t='agora';if(s>=3600)t='há '+Math.floor(s/3600)+'h';else if(s>=60)t='há '+Math.floor(s/60)+'min';else if(s>=10)t='há '+s+'s';txt('ultimoTempo',t)}
function mostrar(){document.getElementById('conteudo').classList.remove('oculto');document.getElementById('erro').classList.add('oculto')}
async function telaCheia(){if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}
function normalizar(v){return String(v||'').trim().split('?')[0].replace(/\/+$/,'')}function valida(v){return /^https:\/\/.+\/exec$/i.test(v)}function msg(t,s){const m=document.getElementById('msg');m.textContent=(s?'✅ ':'❌ ')+t;m.style.color=s?'#0b7a2a':'#b00020'}function txt(id,v){document.getElementById(id).textContent=v??''}function hora(v){const m=String(v||'').match(/(\d{2}:\d{2}:\d{2})$/);return m?m[1]:v}function iniciais(n){const p=String(n||'').trim().split(/\s+/);return p.length>1?(p[0][0]+p[p.length-1][0]).toUpperCase():(p[0]?.[0]||'?').toUpperCase()}function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}